codeit-plake/plake

.eslintignore, .prettierignore, .storybook/preview.ts
스토리북 설정 추가 및 pretterignore, eslintignore 파일 추가
어떤 변경 사항이 있나요?
- 빠른 확인 부탁드립니다.
=> [#6]chore: setting Storybook and ignore files

chromatic.config.json, src/app/page.tsx, src/components/common/ProgressBar.tsx, src/stories/ProgressBar.stories.tsx
ProgressBar 컴포넌트 구현 및 스토리보드 코드 작성
어떤 변경 사항이 있나요?
- 받아온 progress 값(필수)만큼 게이지가 차는 ProgressBar를 구현했습니다.
- progress, width, color를 props로 받아 공통 컴포넌트로 사용할 수 있게 구현했습니다.
- 렌더링 시 0에서 가진 값까지 올라가는 애니메이션을 추가했습니다.
- 컨벤션 확인과 코드 리뷰 부탁드립니다.
=> [#2]feature: progress bar component [PLAK-119]

src/components/common/FavoriteButton.tsx, src/components/common/LoadingDots.tsx, src/components/common/LoadingSpinner.tsx, src/components/common/stories/FavoriteButton.stories.tsx, src/components/common/stories/LoadingDots.stories.tsx, src/components/common/stories/LoadingSpinner.stories.tsx
로딩 컴포넌트 UI 구현 및 Storybook 파일 작성
어떤 변경 사항이 있나요?
- 코드 컨벤션 확인 부탁드립니다
=> [#11]feature: loading component [PLAK-129]

src/components/providers/Modal.tsx, src/components/providers/stories/Modal.stories.tsx
모달 컴포넌트 UI 구현 및 Storybook 파일 작성
- default: 기본 모달
- alert: 알림창 모달
(default와는 모달의 최소, 최대 width가 다릅니다.)
- mobileFull: 모바일에서 전체 화면을 제공하는 모달
(default와 거의 동일하나 모바일 환경에서는 전체화면을 제공합니다. ex. 모임 만들기 페이지)
=> [#20]feature: modal component [PLAK-127]

src/app/globals.css, src/app/page.tsx, src/components/ui/button.tsx, src/components/ui/stories/button.stories.tsx, src/components/ui/tests/button.test.tsx
버튼 공통 컴포넌트 구현 및 테스트 코드 작성
어떤 변경 사항이 있나요?
- 재사용할 수 있는 버튼 컴포넌트의 스타일을 구현했습니다.
- 스토리북과 테스트 코드를 작성하여 문서화 했습니다.
- 코드 검토 부탁드립니다.
=> [#23]feature: button component [PLAK-138]

src/app/gathering/[id]/_components/GatheringInformation.tsx, src/app/gathering/[id]/_components/GatheringReview.tsx, src/app/gathering/[id]/index.ts, src/app/gathering/[id]/page.tsx, src/components/common/DateTimeTag.tsx, src/components/common/stories/DateTimeTag.stories.tsx, src/components/common/tests/DateTimeTag.test.tsx, src/components/gathering-detail/FloatingBar.tsx, src/components/gathering-detail/GatheringInformation.tsx, src/components/gathering-detail/GatheringReviewItem.tsx, src/components/gathering-detail/GatheringReviewList.tsx, src/components/gathering-detail/GathetingImage.tsx, src/components/ui/button.tsx
모임 상세 페이지의 UI를 구현하고 공통 컴포넌트 디테일을 수정했습니다.
어떤 변경 사항이 있나요?
- 상세 페이지의 UI를 구현하였습니다.
- 날짜와 시간을 같이 사용하도록 변경하였습니다.
- date만 필수값으로 받습니다.
- 변경사항 확인한 후 적용해주세요.
=> [#30]feature/30: 모임 상세 페이지 UI 구현 [PLAK-100]

src/components/common/DeadlineTag.tsx, src/components/common/stories/DeadlineTag.stories.tsx
데드라인 태그 컨포넌트 UI를 개발하고 스토리북 코드를 작성했습니다.
어떤 변경 사항이 있나요?
- 구현 부분 검토를 부탁드립니다.
=> [#31]feature: DeadlineTag component [PLAK-117]

next.config.mjs, src/app/gathering/page.tsx, src/components/layout/MainCardItem.tsx, src/components/layout/stories/MainCardItem.stories.tsx
모임 카드 컴포넌트 UI를 개발하고 스토리북 코드를 작성했습니다.
pc, mobile, tablet 환경을 고려해 반응형으로 구현했습니다.
어떤 변경 사항이 있나요?
- default (storybook)
- mobile
- tablet
- 모임과 관련한 데이터들을 props로 전달받습니다.
- 모임 확정(참여자가 5명 이상)인 경우 "개설확정" 버튼이 노출됩니다.
- pc, tablet, mobile 환경에서의 UI를 검토 부탁드립니다.
=> [#17]feature: MainCardItem component [PLAK-118]

src/components/ui/Button.tsx, src/components/ui/Calendar.tsx, src/components/ui/Select.tsx, src/components/ui/Sheet.tsx
=> [#38]rename: ui컴포넌트 파일명 변경

.github/auto_assign.yml, .github/workflows/pr-automation.yml, .github/workflows/pr-quality-checks.yml, package.json, src/components/providers/Modal.tsx
PR 자동화를 위해 설정을 추가하였습니다.
1. PR 생성시 reviewer, assgin, label을 자동으로 등록(pr-automation.yml)
2. PR 생성, 수정, reopen시 lint, type, test, storybook을 실행하는 워크플로우 등록(pr-quality-checks,yml)
어떤 변경 사항이 있나요?
=> [#6]chore: PR 자동화 관련 workflow 설정 추가

src/app/all-reviews/page.tsx
=> [#38]fix: 테스트 에러 수정 시도

.github/workflows/pr-automation.yml, .github/workflows/pr-quality-checks.yml
테스트 로직 브랜치 변경(dev -> main)
어떤 변경 사항이 있나요?
=> [#6]chore: GitHub workflows

src/app/gathering/page.tsx, src/components/common/Dropdown.tsx, src/components/common/FilterCalendar.tsx, src/components/common/GatheringFilterSort.tsx, src/components/common/stories/Dropdown.stories.tsx
모임 목록을 정렬하고 필터링하는 부분의 UI를 구현했습니다.
드롭다운 컴포넌트에 type, placeholder, option props를 추가했습니다. 
어떤 변경 사항이 있나요?
- GatheringFilterSort component
- Dropdown
- 코드 검토를 부탁드립니다.
=> [#36]feature: GatheringFilterSort 공통 컴포넌트 개발 [PLAK-124]

src/app/gathering/page.tsx, src/components/navigations/Tab.tsx, src/components/navigations/stories/Tab.stories.tsx, src/constants/ui.ts, src/hooks/useCustomSearchParams.ts
Tab component를 구현했습니다.
- search parameter를 설정하는 훅을 구현했습니다.
- 전체적인 코드 구현 부분을 검토 부탁드립니다.
=> [#49] feature: Tab component 구현 [PLAK-125]

src/app/gathering/page.tsx, src/components/navigations/SubTab.tsx, src/components/navigations/stories/SubTab.stories.tsx
SubTab component를 구현했습니다.
- 서브탭을 클릭하면 활성화 됩니다.
- 서브탭 데이터(전체, 운동..)가 확정되지 않아서 props로 임시 데이터를 전달했습니다.
- 전체적인 코드 구현 부분을 검토 부탁드립니다.
=> [#48]feature: SubTab 컴포넌트 구현 [PLAK-123]

src/app/error.tsx, src/app/gathering/[id]/_components/GatheringInformation.tsx, src/app/gathering/[id]/_components/GatheringReviewBoard.tsx, src/app/gathering/[id]/error.tsx, src/app/gathering/[id]/page.tsx, src/app/layout.tsx, src/components/gathering-detail/FloatingBar.tsx, src/components/gathering-detail/GatheringImage.tsx, src/components/gathering-detail/GatheringInformation.tsx, src/components/gathering-detail/ParticipantAvatarStack.tsx, src/components/skeletons/gathering-detail/GatheringImageSkeleton.tsx, src/components/skeletons/gathering-detail/GatheringInformationSkeleton.tsx, src/components/skeletons/gathering-detail/GatheringReviewSkeleton.tsx, src/components/ui/Skeleton.tsx, src/constants/gathering.ts, src/constants/queryKeys.ts, src/hooks/gathering/useCancelGathering.ts, src/hooks/gathering/useGatheringDetail.ts, src/hooks/gathering/useJoinGathering.ts, src/hooks/gathering/useParticipants.ts, src/hooks/review/useReviewList.ts, src/types/error.ts, src/types/gathering/index.ts, src/types/user/index.ts
모임 상세페이지 기능을 구현했습니다.
어떤 변경 사항이 있나요?
- 에러 페이지를 구현했습니다.
- 상세페이지 Suspense fallback에 적용될 스켈레톤을 구현했습니다.
- 모임 참여/참여 취소하기 기능을 구현했습니다.
- 모임 주최자일때 모임취소/공유하기 기능을 구현했습니다.
- 쿼리키를 상수로 사용할 수 있도록 지정했습니다.
- 쿼리키랑, type 파일은 같이 사용될 부분이니 검토하시고 다른 의견 있으시면 말씀해주세요!
=> [#30]feature: 모임 상세페이지 기능 구현 [PLAK-103]

.github/workflows/mirror-and-deploy.yml, package-lock.json
Vercel 배포를 위해 Organization의 repository를 개인 repository로 미러링합니다.
어떤 변경 사항이 있나요?
=> [#6]chore: GitHub workflows setting

src/app/gathering/page.tsx
=> [HOTFIX] 빌드 에러 디버깅 (useSearchParams)

.github/workflows/pr-quality-checks.yml, tsconfig.json
=> [#6]chore: PR workflow에 build 조건 추가

src/app/layout.tsx, src/components/modals/create-gathering-modal/CreateGatheringModal.tsx
불필요한 코드 삭제
어떤 변경 사항이 있나요?
- 테스트를 위한 불필요한  코드를 삭제했습니다.
- 확인부탁드립니다.
=> [#51]remove: 테스트를 위한 불필요한 코드 삭제

src/components/skeletons/MainCardItemSkeleton.tsx, src/components/skeletons/ReviewCardItemSkeleton.tsx, src/components/skeletons/stories/MainCardItemSkeleton.stories.tsx, src/components/skeletons/stories/ReviewCardItemSkeleton.stories.tsx
MainCardItem, ReviewCardItem 컴포넌트 스켈레톤 제작
어떤 변경 사항이 있나요?
[MainCardItemSkeleton]
[ReviewCardItemSkeleton]
=> [#63]feature: CardSkeleton 컴포넌트 개발 [PLAKE-130]

src/components/common/DeadlineTag.tsx, src/components/common/stories/DeadlineTag.stories.tsx, src/components/gathering-detail/GatheringImage.tsx, src/components/layout/MainCardItem.tsx, src/components/layout/stories/MainCardItem.stories.tsx
DeadlineTag 마감일, 시간 판단 부분을 수정하고 MainCardItem이 마감됐을 경우의 UI를 추가했습니다.
- DeadlineTag 수정
- 모임이 마감됐을 경우의 MainCardItem
- 코드 검토를 부탁드립니다!
=> [#65] 모임이 마감됐을 경우의 MainCardItem, DeadlineTag UI 변경

next.config.mjs, src/app/gathering/page.tsx, src/components/layout/MainCardItem.tsx, src/components/layout/MainCardList.tsx, src/components/layout/stories/MainCardItem.stories.tsx, src/constants/queryKeys.ts, src/hooks/gathering/useGatheringList.ts, src/services/Service.ts, src/services/gathering/GatheringService.ts
모임 카드를 감싸는 MainCardList 컴포넌트를 개발했습니다.
- MainCardItem의 클릭 영역을 변경했습니다.
- Service 계층 분리
- api를 호출하는 클래스를 정의하는 부분입니다. 기본 Service 객체를 상속받는 GatheringService를 구현했습니다.
- Service.ts 확인을 부탁드립니다. 전체적인 코드 구현에 대한 검토를 부탁드립니다.
=> [#35] MainCardList 컴포넌트 개발, Service layer 분리 [PLAK-140]

src/app/gathering/page.tsx, src/components/navigations/FilterTab.tsx
FilterTab 이름 및 경로 변경
어떤 변경 사항이 있나요?
=> [Fix] FilterTab 이름 및 경로 변경

.github/workflows/pr-quality-checks.yml, src/app/gathering/page.tsx, src/components/boundary/FetchBoundary.tsx, src/components/layout/MainCardList.tsx, src/components/skeletons/MainCardListSkeleton.tsx, src/components/ui/FetchError.tsx, src/hooks/gathering/useGatheringList.ts
MainCardList Suspense, ErrorBoundary를 적용했습니다.
- ErrorBoundary와 관련한 재사용 가능한 코드를 공통 컴포넌트로 구현했습니다. (FetchErrorBoundary, FetchError)
- FetchErrorBoundary
- 역할1) ErrorBoundary. Fetch시의 에러를 판단하는 부분. 에러라면(hasError=true) FetchError(fallback component)를 보여줍니다.
- 역할2) Suspense. 데이터를 가져와서 HTML을 만들고 JavaScript를 hydrate하는 등의 일련의 과정을(비동기 작업들) 수행하는 동안의 대체 UI를 표시한다.
- FetchError : fallback component (FetchError 발생시 보여주는 UI)
- 전체적인 코드 구현을 확인 부탁드립니다.
=> [#72] feature: MainCardList Suspense, ErrorBoundary 적용 [PLAK-176]

src/app/gathering/[id]/page.tsx, src/app/globals.css, src/app/page.tsx, src/components/common/DateTimeTag.tsx, src/components/common/stories/DateTimeTag.stories.tsx, src/components/common/stories/Rating.stories.tsx, src/components/common/tests/DateTimeTag.test.tsx, src/components/common/tests/__snapshots__/DateTimeTag.test.tsx.snap, src/components/gathering-detail/FloatingBar.tsx, src/components/gathering-detail/GatheringInformation.tsx, src/components/gathering-detail/GatheringReviewItem.tsx, src/components/gathering-detail/GatheringReviewList.tsx, src/components/gathering-detail/ParticipantAvatarStack.tsx, src/components/layout/MainCardItem.tsx, src/components/layout/ReviewCardList.tsx, src/hooks/gathering/useCancelGathering.ts, src/hooks/gathering/useGatheringDetail.ts, src/hooks/gathering/useJoinGathering.ts, src/hooks/review/useReviewList.ts, src/services/HttpClient.ts, src/services/Service.ts, src/services/gathering/GatheringService.ts, src/services/review/ReviewService.ts
API Instance 적용 및 핸들러 수정
어떤 변경 사항이 있나요?
- API 인스턴스를 적용했습니다.
- 빈 값일 때의 UI를 구현했습니다.
- 모달 적용 및 핸들러를 추가했습니다.
- 테스트 코드 및 스토리북 코드를 수정했습니다.
- 코드 확인 부탁드립니다.
=> [#30]feature: API Instance 적용 및 핸들러 추가

src/app/gathering/layout.tsx, src/app/layout.tsx, src/components/common/Dropdown.tsx, src/components/modals/Modal.tsx, src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx, src/components/modals/create-gathering-modal/CreateGatheringModal.tsx, src/components/modals/create-gathering-modal/DateTimePicker.tsx, src/components/modals/create-gathering-modal/ImageUploader.tsx, src/components/modals/create-gathering-modal/ServiceSelector.tsx, src/components/modals/create-gathering-modal/SubServiceSelector.tsx, src/components/modals/edit-profile-modal/EditProfileModal.tsx, src/components/providers/ModalProvider.tsx, src/constants/gathering.ts, src/hooks/gathering/useCancelGathering.ts, src/hooks/gathering/useCreateGathering.ts, src/hooks/useCalendar.ts, src/schemas/gatheringSchema.ts, src/services/gathering/GatheringService.ts
모임 만들기 유효성 검사 및 hook 구현
어떤 변경 사항이 있나요?
- 모임/마감 날짜의 유효성 검사를 수정하였습니다. (마감 날짜는 모임 날짜 이전이어야 한다.)
- 모임 생성을 위한 hook을 구현하고 API를 연결했습니다.
- zustand의 useShallow를 사용하여 state를 구독할때의 렌더링을 최적화시켰습니다.
- 코드 검토 부탁드립니다.
=> [#51]feature: 모임 만들기 유효성 검사 및 hook 구현 [PLAK-178]

src/components/auth/TokenValidator.tsx
=> [#56]fix: TokenValidator 수정

src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx, src/app/gathering/[tab]/layout.tsx, src/components/modals/create-gathering-modal/CreateGatheringModal.tsx, src/components/navigations/FilterTab.tsx, src/components/navigations/MainTab.tsx
모임 목록페이지에 모임 만들기 모달 버튼을 추가했습니다.
어떤 변경 사항이 있나요?
- 로그인 여부와 상관없이 목록페이지에서 모임 만들기 모달 버튼을 볼 수 있습니다.
- 로그인 유저의 경우에만 모임 만들기 모달에 접근 가능합니다.
- 비로그인 유저가 모임 만들기 모달 버튼을 클릭하면 로그인 페이지로 이동합니다.
- CreateGatheringModal 컴포넌트 수정에 대한 확인을 부탁드립니다.
=> [#72]feature: 모임 목록페이지 모임 만들기 모달 추가

package-lock.json, package.json, src/app/(home)/_components/MainContent.tsx, src/app/(home)/_components/MainReviewContent.tsx, src/app/(home)/_components/MainReviewItem.tsx, src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx, src/app/gathering/detail/[id]/_components/FloatingBar.tsx, src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx, src/app/gathering/detail/[id]/_components/GatheringReviewList.tsx, src/app/gathering/detail/[id]/page.tsx, src/components/modals/create-gathering-modal/DateTimePicker.tsx, src/components/modals/create-gathering-modal/TimePicker.tsx, src/components/ui/Pagination.tsx, src/constants/review.ts, src/hooks/useCalendar.ts, src/types/review/main-review.ts, tailwind.config.ts
코드 구조 및 TimePicker 기능 수정
어떤 변경 사항이 있나요?
- 코드 구조를 변경했습니다.
- TimePicker 요소 클릭 시 닫히는 이벤트를 제거하고, 닫힌 이후에도 데이터가 유지되도록 수정했습니다.
- 코드 검토 부탁드립니다.
=> [#30]fix: 코드 구조 및 TimePicker 기능 수정

.github/workflows/mirror-and-deploy.yml, .github/workflows/pr-quality-checks.yml, src/app/api/auths/user/route.ts, src/app/mypage/_components/my-card-list/MyCreateCardList.tsx, src/app/mypage/_components/my-card-list/MyReviewCardList.tsx, src/app/mypage/_components/my-card-list/MyWrittenCardList.tsx, src/app/mypage/gathering/page.tsx, src/app/mypage/reviews/page.tsx, src/constants/queryKeys.ts, src/hooks/auth/useCheckUser.ts, src/hooks/gathering/useMyGatheringList.ts, src/services/auth/AuthService.ts, src/types/gathering/index.ts
마이페이지 기능 구현 완료
어떤 변경 사항이 있나요?
- 마이페이지 뷰 전체 구현
- 나의 모임, 나의 리뷰(작성 가능한 리뷰, 작성한 리뷰), 내가 만든 모임 항목 UI 구성 및 데이터 연결
- 카드 목록 무한 스크롤 적용
- 각 리스트의 정렬 기준(최신순) 적용
- 서버 사이드에서 유저 정보를 사전 요청하여 페이지 진입 시 flickering 없이 렌더링
- 사용자 ID 기반 데이터 요청을 위한 prefetch 및 Hydration 구성
- 마이페이지 기능 개발이 완료되어 전체 구조 및 요청 흐름 확인 부탁드립니다.
- 추가적으로 UX 개선이 필요한 포인트가 있다면 제안 주시면 반영하겠습니다.
=> [#67]feature: 마이페이지 기능 구현 완료

src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx, src/app/all-reviews/[tab]/_components/ReviewSubTab.tsx, src/app/gathering/detail/[id]/_components/FloatingBar.tsx, src/app/gathering/detail/[id]/_components/GatheringReviewBoard.tsx, src/app/gathering/detail/[id]/_components/GatheringReviewList.tsx, src/app/join/_components/JoinForm.tsx, src/app/login/_components/LoginForm.tsx, src/components/common/Avatar.tsx, src/components/common/GatheringFilterSort.tsx, src/components/layout/ReviewCardItem.tsx, src/components/modals/Modal.tsx, src/components/modals/confirm-alert-modal/ConfirmAlertModal.tsx, src/components/navigations/SideBar.tsx, src/components/ui/Sheet.tsx
=> [#82]fix: 기타 css 수정

src/app/favorites/_components/GatheringFavoriteList.tsx, src/app/favorites/page.tsx, src/app/gathering/detail/[id]/_components/GatheringDetailInformation.tsx, src/components/common/FavoriteButton.tsx, src/components/common/FavoriteButtonWrapper.tsx, src/components/layout/MainCardItem.tsx, src/components/layout/MainCardList.tsx, src/components/layout/stories/MainCardItem.stories.tsx
모임 찜하기 기능을 구현했습니다. 찜한 모임의 아이디는 localStorage에 저장됩니다.
어떤 변경 사항이 있나요?
- 전체적인 코드 구현 확인을 부탁드립니다.
=> [#102]feature: 모임 찜하기 기능 구현

src/app/mypage/layout.tsx, src/components/common/Rating.tsx, src/hooks/gathering/useCancelGathering.ts, src/hooks/gathering/useCreateGathering.ts, src/hooks/useCalendar.ts
=> [#113]fix: 전체 서비스 디버깅

src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx, src/app/all-reviews/[tab]/_components/ReviewSubTab.tsx, src/app/favorites/_components/FavoriteList.tsx, src/app/mypage/_components/ReviewTab.tsx, src/components/common/FilterCalendar.tsx, src/components/common/GatheringFilterSort.tsx, src/components/layout/MainCardItem.tsx, src/components/navigations/NavTab.tsx, src/components/navigations/SubTab.tsx
모임 찾기, 즐겨찾기 페이지에서 변수명, 스타일 수정
어떤 변경 사항이 있나요?
- 변수명을 수정했습니다.
- MainCardItem에서 모임이름의 max-width를 수정했습니다.
- 전체적인 코드 구현 확인 부탁드립니다.
=> fix: 모임 찾기 페이지, 즐겨찾기 페이지 수정

src/app/mypage/_components/my-card-list/MyReviewCardList.tsx, src/utils/myCardHelpers.tsx, src/utils/rating.ts
리뷰 등록 기능 변경 및 리뷰 점수 등록 기능 디버깅
어떤 변경 사항이 있나요?
- 리뷰 등록 기능 변경
- befor: 모임 날짜 지난 이후 리뷰 등록 가능
- after: 모임 참여시 리뷰 등록 가능
=> [#113]refactor: 리뷰 등록 기능 변경

src/app/mypage/_components/my-card-list/MyCardList.tsx, src/app/mypage/_components/my-card-list/MyCreateCardList.tsx, src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
삭제된 모임 필터링 로직 추가 
어떤 변경 사항이 있나요?
- DTO 확인 바랍니다.
=> [#113]fix: 삭제된 모임 필터링 로직 추가

src/app/gathering/detail/[id]/_components/GatheringImage.tsx
상세 페이지 태그 부분 dateTime -> registrationEnd 변경
어떤 변경 사항이 있나요?
- 상세 페이지 태그 부분 dateTime -> registrationEnd 변경
- ex. CropDetail create메서드 확인 바랍니다, DTO 확인 바랍니다.
=> [#30]fix: dateTime -> registrationEnd 변경

src/app/mypage/_components/my-card-list/MyCardList.tsx, src/app/mypage/_components/my-card-list/MyCreateCardList.tsx, src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
핉터 로직 에러 수정
어떤 변경 사항이 있나요?
- DTO 확인 바랍니다.
=> [#113]refactor: 필터 로직 에러 수정

src/app/gathering/detail/[id]/_components/GatheringImage.tsx, src/app/mypage/_components/my-card-list/MyCardList.tsx, src/app/mypage/_components/my-card-list/MyCreateCardList.tsx, src/app/mypage/_components/my-card-list/MyReviewCardList.tsx
=> [Deploy] v1.0.2 서비스 배포

src/components/modals/create-gathering-modal/CreateGatheringModal.tsx, src/hooks/gathering/useCancelGathering.ts, src/hooks/gathering/useCreateGathering.ts
- 모임 삭제 후 이전 페이지로 이동
- 모임 생성 모달 동작 변경
어떤 변경 사항이 있나요?
- DTO 확인 바랍니다.
=> [#113]refactor: 모임 삭제 후 이전 페이지로 이동 + 모임 생성 모달 동작 변경

src/components/common/DeadlineTag.tsx, src/components/common/Dropdown.tsx, src/components/layout/MainCardItem.tsx, src/utils/gatheringFilterParams.ts
모임페이지의 정렬 버그를 수정하고 UI를 수정했습니다.
어떤 변경 사항이 있나요?
- 정렬 드롭다운의 크기를 변경했습니다.
- 모임이 종료됐을 경우 DeadlineTag 컴포넌트는 보이지않게 수정했습니다.
- 전체적인 코드구현 확인을 부탁드립니다.
=> [#72]모임 페이지의 정렬 부분 버그 수정과 UI 수정[PLAK-184]

.github/workflows/mirror-and-deploy.yml, .github/workflows/pr-quality-checks.yml
Sentry 설정 파일 추가
어떤 변경 사항이 있나요?
- DTO 확인 바랍니다.
=> [#6]chore: Sentry 설정 파일 추가

.gitignore, next.config.mjs, package-lock.json, package.json, sentry.edge.config.ts, sentry.server.config.ts, src/instrumentation-client.ts, src/instrumentation.ts
sentry 연동
어떤 변경 사항이 있나요?
[설정 내용]
- 전체적인 코드 구현 확인을 부탁드립니다.
=> [#135]feature: sentry 연동[PLAK-186]

package-lock.json, package.json, src/app/gathering/[tab]/page.tsx, src/components/layout/MainCardList.tsx, src/components/navigations/FilterTab.tsx, src/components/navigations/MainTab.tsx, src/components/navigations/SubTab.tsx, src/components/navigations/tests/MainTab.test.tsx, src/components/navigations/tests/SubTab.test.tsx, src/constants/ui.ts, src/utils/gatheringFilterParams.ts
모임 목록페이지에서 탭을 클릭시 변경되는 URL params의 type value를 수정했습니다.
MainTab, SubTab 컴포넌트 유닛 테스트를 진행했습니다.
어떤 변경 사항이 있나요?
- 전체적인 코드 구현 확인을 부탁드립니다.
=> [#143]MainTab, SubTab 컴포넌트 유닛 테스트[PLAK-175]

jest.config.ts, src/components/common/tests/FavoriteButton.test.tsx, src/constants/queryKeys.ts, src/hooks/auth/tests/useCheckUser.test.ts, src/hooks/auth/useCheckUser.ts, src/hooks/auth/useUpdateUser.ts, src/utils/myCardHelpers.tsx, src/utils/test-utils/userMocking.ts, src/utils/tests/myCardHelpers.test.tsx
auth 훅 일부 리팩토링 및 테스트 코드 추가
어떤 변경 사항이 있나요?
- `fetchUserId` 유틸 함수 분리
- `prefetchCheckUser` 내부 queryKey 사용 방식 개선
- `authService.getUser` mock 구조 정리
- 관련 테스트 코드 작성 (성공/실패 캐시 검증 포함)
- `mockUser` 유틸 추가 및 store mocking 패턴 명확화
- authService.getUser mock 관련 구조 확인 부탁드립니다.
=> [#146]test: auth 훅 일부 리팩토링 및 테스트 코드 추가

jest.setup.ts, src/app/all-reviews/[tab]/_components/ReviewFilterSort.tsx, src/components/common/Dropdown.tsx, src/components/common/GatheringFilterSort.tsx, src/components/common/SortDropdown.tsx, src/components/common/stories/Dropdown.stories.tsx, src/components/common/tests/Dropdown.test.tsx, src/components/common/tests/SortDropdown.test.tsx, src/components/navigations/FilterTab.tsx, src/components/navigations/tests/FilterTab.test.tsx, src/utils/gatheringFilterParams.ts
Dropdown, SortDropdown, FilterTab 컴포넌트에 대한 테스트와 리팩토링을 진행했습니다.
어떤 변경 사항이 있나요?
- 확인을 부탁드립니다.
=> [#143]test: 공통 컴포넌트 유닛 테스트 & 리팩토링

jest.config.ts, src/app/mypage/_components/ReviewTab.tsx, src/app/mypage/_components/my-card-item/MyCardAction.tsx, src/app/mypage/_components/my-card-list/MyCardList.tsx, src/app/mypage/_components/my-card-list/MyCreateCardList.tsx, src/app/mypage/_components/my-card-list/MyReviewCardList.tsx, src/app/mypage/_components/tests/MyCardAction.test.tsx, src/app/mypage/_components/tests/MyCardList.test.tsx, src/app/mypage/_components/tests/MyCreateCardList.test.tsx, src/app/mypage/_components/tests/MyReviewCardList.test.tsx, src/app/mypage/_components/tests/MyWrittenCardList.test.tsx, src/app/mypage/_components/tests/ReviewTab.test.tsx, src/components/layout/ReviewCardItem.tsx, src/constants/ui.ts, src/hooks/review/tests/useCreateReview.test.tsx, src/hooks/review/useCreateReview.ts
마이페이지 비지니스 로직  테스트 코드 작성
어떤 변경 사항이 있나요?
- 마이페이지 내 주요 컴포넌트에 대한 테스트 코드 작성
- MyCardAction에 대해 버튼 type별 이벤트 테스트 (cancel, viewReview, writeReview)
- 예외적인 type 값 처리 테스트 추가
- 모든 버튼에 대한 e.preventDefault() 호출 여부 확인 => 테스트 커버리지 100% 달성 (69% → 100%)
- 테스트 커버리지 외에도 코드 구조에 대한 개선점이 있다면 코멘트 부탁드립니다.
- MyCardList, MyReviewCardList, MyCreateCardList 등 리스트 컴포넌트들은 테스트 로직이 대부분 유사하므로, 한 파일만 대표로 확인해주셔도 됩니다.
- (MyProfile 컴포넌트는 테스트 코드 작성 예정입니다. | 외부 의존성이 많아서 보류)
=> [#146]test: 마이페이지 비지니스 로직  테스트 코드 작성

src/app/favorites/_components/FavoriteList.tsx, src/app/login/_components/LoginForm.tsx, src/components/common/FavoriteButtonWrapper.tsx, src/components/navigations/NavList.tsx, src/constants/favorite.ts, src/hooks/auth/useLogout.ts, src/hooks/useFavorite.ts, src/services/gathering/AnonGatheringService.ts
찜하기 기능에 대한 리팩토링을 진행했습니다.
어떤 변경 사항이 있나요?
- 찜한 모임 최대수 상수 설정
- 모임 찜하기 관련 useFavorite hook 구현
- 로그아웃, 로그인 시 즐겨찾기 목록(localstorage) 초기화
- Navlist에 찜한 모임 수 데이터 반영
- 로그인, 로그아웃 시 즐겨찾기 목록 초기화되는 로직 확인을 부탁드립니다.
=> [#102]refact: 찜하기 기능 리팩토링[PLAK-185]

src/app/mypage/_components/tests/MyCardCancelButton.test.tsx, src/app/mypage/_components/tests/MyCardViewReviewButton.test.tsx, src/app/mypage/_components/tests/MyCardWriteReviewButton.test.tsx, src/app/mypage/_components/tests/MyProfile.test.tsx, src/app/mypage/_components/tests/ReviewTab.test.tsx, src/components/common/Rating.tsx, src/components/modals/BackDrop.tsx, src/components/modals/Modal.tsx, src/components/modals/create-review-modal/CreateReviewModal.tsx, src/components/modals/tests/CreateReviewModal.test.tsx, src/components/modals/tests/EditProfileModal.test.tsx, src/components/modals/tests/Modal.test.tsx, src/components/skeletons/MyProfileSkeleton.tsx, src/hooks/auth/tests/useUpdateUser.test.tsx, src/hooks/auth/useUpdateUser.ts, src/utils/test-utils/setupModalRoot.ts
마이페이지 및 공통 범위 테스트 작성
어떤 변경 사항이 있나요?
- 마이페이지 관련 UI/로직 안정성을 검증하기 위한 테스트 코드 작성
- MyProfile
- 다음 컴포넌트의 단위 테스트가 포함됩니다:
- CreateReviewModal
- EditProfileModal
- Modal
- 훅 테스트 작성
- useUpdateUser
- MyProfile 테스트 내 조건 분기 확인 부탁드립니다.
=> [#146]test: 마이페이지 및 공통 범위 테스트 작성

src/app/favorites/_components/FavoriteList.tsx, src/components/layout/ClosedMainCardItem.tsx, src/components/layout/MainCardImage.tsx, src/components/layout/MainCardItem.tsx, src/components/layout/MainCardList.tsx, src/components/layout/stories/MainCardItem.stories.tsx, src/components/layout/tests/MainCardItem.test.tsx, src/components/layout/tests/MainCardList.test.tsx, src/utils/gatheringFilterParams.ts, src/utils/test-utils/gatheringMocking.ts, src/utils/tests/gatheringFilterParams.test.ts
MainCard 관련 컴포넌트와 gatheringFilterParams utils에 대한 유닛 테스트 코드를 작성했습니다.
어떤 변경 사항이 있나요?
- 코드 확인을 부탁드립니다.
=> [#143]test: MainCard관련 컴포넌트, utils 유닛 테스트 & 리팩토링

src/app/favorites/_components/FavoriteList.tsx, src/app/favorites/layout.tsx, src/app/gathering/[tab]/_components/Banner.tsx, src/app/gathering/[tab]/_components/CreateGatheringModalWrapper.tsx, src/app/gathering/[tab]/layout.tsx
모임 목록 페이지, 찜한 목록 페이지 수정
어떤 변경 사항이 있나요?
- 모바일일 때의 모임 만들기 버튼 디자인을 수정
- 찜한 모임, 모임 목록 페이지 layout 디자인 변경
- 코드 확인을 부탁드립니다.
=> [#169]design: 모임 목록 페이지, 찜한 목록 페이지 수정

src/hooks/tests/useIntersectionObserver.test.tsx, src/utils/test-utils/intersectionObserverTestHelper.ts
useIntersectionObserver 훅에 대한 유닛 테스트를 진행했습니다.
어떤 변경 사항이 있나요?
- 세부사항을 항목으로 설명해주세요
- 코드 확인을 부탁드립니다.
=> [#143]test: useIntersectionObserver 훅 유닛 테스트

src/app/mypage/page.tsx, src/components/modals/tests/CreateReviewModal.test.tsx, src/hooks/review/tests/useCreateReview.test.tsx, src/hooks/review/useCreateReview.ts
CreateReviewModal 테스트 불안정성 개선
어떤 변경 사항이 있나요?
CreateReviewModal 테스트가 최근 머지된 코드 이후로 계속 실패하는 현상을 해결했습니다.
- 비동기 함수인 `findByRole`을 사용하여 버튼을 찾고 있어, 버튼 요소의 참조가 변경되는 상황 발생
- 이로 인해 클릭 이벤트가 제대로 처리되지 않아 `handleCreateReview` 함수가 호출되지 않는 문제 발생
✅ `findByRole` 대신 동기 함수인 `getByRole`을 사용하여 문제 해결
(기존 테스트의 불안정성이 다른 코드와 결합되면서 드러난 문제였으며, 이번 수정으로 테스트의 신뢰성과 일관성을 개선했습니다.)
- 비동기 처리 로직이 적절하게 수정되었는지 검토 부탁드립니다.
=> [#146]test: CreateReviewModal 테스트 불안정성 개선

package-lock.json, package.json, src/components/common/Rating.tsx, src/components/navigations/SideBar.tsx
=> [#164]refactor: 라이트하우스 접근성 점수 개선

src/app/layout.tsx
dynamic import 제거
어떤 변경 사항이 있나요?
- 코드 검토 바랍니다.
=> [#51]fix: dynamic import 제거

next.config.mjs, src/app/mypage/_components/my-card-list/MyCardList.tsx, src/app/mypage/_components/my-card-list/MyCreateCardList.tsx, src/app/mypage/_components/my-card-list/MyReviewCardList.tsx, src/app/mypage/_components/my-card-list/MyWrittenCardList.tsx
Vercel 이미지 최적화 초과로 인한 unoptimized 설정 추가 및 UI 수정
어떤 변경 사항이 있나요?
- Vercel 무료 요금제에서는 이미지 최적화가 월 5,000회로 제한되는데, 현재 프로젝트는 해당 쿼터를 초과하여 배포 환경에서 next/image 컴포넌트로 불러오는 이미지가 HTTP 402 에러로 인해 로드되지 않는 문제가 발생했습니다.
- 이에 따라, 긴급 대응으로 next.config.js에 images.unoptimized: true 옵션을 추가하여 이미지 최적화를 비활성화하고, 정적 이미지처럼 처리되도록 설정하였습니다.
- 4월 15일(내일) 최종 발표인 만큼, 서비스 동작의 안정성이 우선순위라고 판단하여 해당 설정을 빠르게 반영하게 되었습니다.
이후 발표가 종료된 뒤에는 이미지 최적화 전략을 재검토할 예정입니다.
- 이미지 로드 정상 여부 및 UI 상 깨지는 부분이 없는지도 함께 확인 부탁드립니다.
=> [#113]fix: Vercel 이미지 최적화 초과로 인한 unoptimized 설정 추가 및 UI 수정

src/app/favorites/_components/FavoriteBanner.tsx, src/app/gathering/[tab]/_components/Banner.tsx, src/utils/myCardHelpers.tsx
=> [#113]fix: 디자인 시안 반영을 위한 UI 일부 수정

src/actions/user-check-action.ts, src/actions/user-signin-action.ts, src/app/gathering/detail/[id]/_components/GatheringDetailInformation.tsx, src/app/login/_components/LoginForm.tsx, src/utils/cookieToken.ts
서버액션에서 한꺼번에 하던 쿠키 설정을 클라이언트로 이동해서 해결
=> [#193]fix: 쿠키 설정 이슈 해결
